import { readFile } from "node:fs/promises";
import path from "node:path";
import type { ValidationFinding } from "../../types/index.js";
import { STRUCTURAL_FILES } from "../../types/validation.js";
import { listMarkdownFiles } from "./shared.js";

const REQUIRED_HEADINGS = ["## Overview", "## Source Coverage"];

/**
 * Check that module pages contain required section headings.
 * AC-4.3c: every module page must have overview and source-coverage sections.
 * Title (# heading) is prepended by assembly, so we don't check for it here.
 *
 * Only checks module pages (files starting with "# "), not structural files
 * like overview.md.
 *
 * Missing required sections produce "error" severity findings.
 */
export const checkRequiredSections = async (
  outputPath: string,
): Promise<ValidationFinding[]> => {
  const markdownFiles = await listMarkdownFiles(outputPath);

  if (markdownFiles.length === 0) {
    return [];
  }

  const findings: ValidationFinding[] = [];

  for (const filePath of markdownFiles) {
    const fileName = path.basename(filePath);

    // Skip structural files (overview.md, etc.)
    if (STRUCTURAL_FILES.has(fileName)) {
      continue;
    }

    const contents = await readFile(filePath, "utf8");

    // Only check pages generated by the agentic path, which always include
    // both ## Overview and ## Source Coverage from assembleAgentPage().
    // Pages from the one-shot path have a different structure and may not
    // have these exact headings. We identify agentic pages by checking if
    // at least one of the required headings is present — a page that has
    // neither is a one-shot/legacy page and should be skipped.
    if (!contents.startsWith("# ")) {
      continue;
    }

    const presentCount = REQUIRED_HEADINGS.filter((h) =>
      contents.includes(h),
    ).length;

    // Skip pages that have none of the required headings (one-shot pages)
    if (presentCount === 0) {
      continue;
    }

    for (const heading of REQUIRED_HEADINGS) {
      if (!contents.includes(heading)) {
        findings.push({
          category: "required-section",
          filePath,
          message: `Missing required section "${heading}" in ${filePath}`,
          severity: "error",
        });
      }
    }
  }

  return findings;
};
